# Generated by Django 5.0.3 on 2024-05-28 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_interest_purpose_user_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=20, null=True)),
                ('degree', models.CharField(blank=True, max_length=20, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.user_detail')),
            ],
        ),
    ]
