# Generated by Django 5.0.3 on 2024-05-02 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('course_date', models.DateField()),
                ('course_price', models.IntegerField()),
                ('course_learning_credits', models.IntegerField()),
                ('course_rating', models.FloatField()),
                ('course_authors', models.ManyToManyField(default=None, related_name='courseses', to='course_app.authors')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.course')),
                ('course_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.location')),
                ('course_mode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course_app.mode')),
                ('course_sponsors', models.ManyToManyField(default=None, related_name='courseses', to='course_app.sponsors')),
            ],
        ),
    ]
